#pragma once

#include <windows.h>

#define BLACK_COLOR 0
#define BLUE_COLOR FOREGROUND_BLUE
#define GREEN_COLOR FOREGROUND_GREEN
#define CYAN_COLOR (FOREGROUND_BLUE | FOREGROUND_GREEN)
#define RED_COLOR FOREGROUND_RED
#define MAGENTA_COLOR (FOREGROUND_RED | FOREGROUND_BLUE)
#define YELLOW_COLOR (FOREGROUND_RED | FOREGROUND_GREEN)
#define GRAY_COLOR (FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE)
#define DARK_GRAY_COLOR FOREGROUND_INTENSITY
#define LIGHT_BLUE_COLOR (FOREGROUND_BLUE | FOREGROUND_INTENSITY)
#define LIGHT_GREEN_COLOR (FOREGROUND_GREEN | FOREGROUND_INTENSITY)
#define LIGHT_CYAN_COLOR (FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY)
#define LIGHT_RED_COLOR (FOREGROUND_RED | FOREGROUND_INTENSITY)
#define LIGHT_MAGENTA_COLOR (FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY)
#define LIGHT_YELLOW_COLOR (FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY)
#define RESET_COLOR (FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY)

void SetConsoleColor(WORD color) {
    HANDLE console = GetStdHandle(STD_OUTPUT_HANDLE);
    SetConsoleTextAttribute(console, color);
}